### ISSUE TITLE
Improved-Spread-Spectrum(iss_improve)

### ISSUE THREAD

**Issue by ramya1782** [ktekeli/audio-steganography-algorithms#3]
Hello Mr Tekeli, i was evaluating the improved Spread spectrum (2).Its really works well.Wanted to know the major difference between Spread spectrum 1 and 2 and also  part of the code in  improved Spread spectrum (2) ,iss_improve.p, which is obfuscated. Can i get the code for  iss_improve.p ?

**Comment by ktekeli** [comment]
Hello, I am sorry for the late reply. You can reach the source codes of all methods [here](http://hdl.handle.net/11607/3209) at the end of my MSc thesis.
Best regards.

**Comment by ramya1782** [comment]
Thank you very much.

Regards,
Ramya Aradhya
