### ISSUE TITLE
Attack Problem

### ISSUE THREAD

**Issue by xiaoluo45678** [ktekeli/audio-steganography-algorithms#5]
The program works well! But I have a question to ask you, is if I want to join the common noise attack, this audio file will be damaged, can not recover, how to solve this ？Have a nice day!

**Comment by 28286575show** [comment]
您好！您的邮件已经收到，谢谢！

**Comment by xiaoluo45678** [comment]
My email address is 3111612303@qq.com

**Comment by 28286575show** [comment]
您好！您的邮件已经收到，谢谢！

**Comment by ktekeli** [comment]
I have been busy for a while, sorry for the late answer. You may try different methodsin order to obtain better results against common attacks. Spread spectrum on low frequency or echo hiding would work fine against noise attack. Best regards.
