### ISSUE TITLE
Is the computation in echo_enc_single.m right?

### ISSUE THREAD

**Issue by njusq** [ktekeli/audio-steganography-algorithms#6]
Hi! Thank you for your implementation which helps me a lot!
You use filter function to generate echo signal echo_zro and echo_one in echo_enc_single.m from line 43 to line 47.
```
k0 = [zeros(d0, 1); 1]*alpha;        %Echo kernel for bit0
k1 = [zeros(d1, 1); 1]*alpha;        %Echo kernel for bit1
echo_zro = filter(k0, 1, signal);    %Echo signal for bit0
echo_one = filter(k1, 1, signal);    %Echo signal for bit1
```
However, it seems more likely to be time spread method from [Kadir's thesis](http://hdl.handle.net/11607/3209) in page 83.
The actual single kernel method's computation maybe should be:
```
echo_zro = [zeros(d0,s.ch);signal(1:end-d0,:)]*alpha;
echo_one = [zeros(d1,s.ch);signal(1:end-d1,:)]*alpha;
```
Is my understanding right?

**Comment by 28286575show** [comment]
您好！您的邮件已经收到，谢谢！

**Comment by ktekeli** [comment]
Hello, both codes are the same in what you have written. Filter function does exactly the same thing, so I used that in github. I just tried to explain the code clearly in my MSc thesis, so I used an easier syntax there. Time spread is a different method that you spread more echoes along the signal, and you can find more information about that method in thesis. Don't be confused with the syntax, they both do the same job. Best regards.
