### ISSUE TITLE
Multiple track selection

### ISSUE THREAD

**Issue by stranger-ranger** [ktekeli/audio-steganography-algorithms#8]
I would like to know if it is possible to modify MATLAB code to perform processing of multiple audio files at once? At the moment I'm having trouble using ECHO hiding with single kernel to embed the same information for multiple tracks.

**Comment by 28286575show** [comment]
您好！您的邮件已经收到，谢谢！

**Comment by ktekeli** [comment]
Hello, I have been working on my PhD thesis in a different field recently. I have developed a steganography module for researchers that can embed the same information in multiple audio files and assess its robustness against various attacks. I plan to upload it as soon as my research paper is published.

**Comment by stranger-ranger** [comment]
Thank you so much for the quick reply! I wish you the best of luck with your PhD thesis!
