### ISSUE TITLE
Is this project made with linux support in mind?

### ISSUE THREAD

**Issue by ddogfoodd** [ktekeli/audio-steganography-algorithms#9]
When trying to run a script using octave, I get this error:

`line 1: /mp3bin/mp3info.x86_64-pc-linux-gnu: No such file or directory`

Those seem to be missing in all `mp3bin` directories.

Is this project supposed to be run on Windows or MacOS instead?

**Comment by 28286575show** [comment]
您好！您的邮件已经收到，谢谢！

**Comment by ktekeli** [comment]
Hello, it was written in MATLAB on Windows, mp3bin contains external libraries to have mp3 conversion using LAME codec. You can look for Linux alternatives if you need mp3 file format. Good luck!
